### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Teicu** [secengjeff/rapidresetclient#1]
Hi, 

it seems that no matter what URL I use, the answer is the same, I mean: 

_--- Summary ---
Frames sent: HEADERS = 10, RST_STREAM = 10
Frames received: 2
Total time: 1.09 seconds (9 rps)_ 

And then I would like to understand which is actually vulnerable and which is not? 

Cheers

**Comment by secengjeff** [comment]
Can you share the full output? With a wait of 500 ms (for example) you should see something like:

```
Received frame: [FrameHeader SETTINGS flags=ACK len=0]
Received frame: [FrameHeader WINDOW_UPDATE len=4]
[3] Sent HEADERS on stream 3
[3] Sent RST_STREAM on stream 3
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=3 len=175]
Received frame: [FrameHeader DATA flags=END_STREAM stream=3 len=1256]
[5] Sent HEADERS on stream 5
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=5 len=87]
Received frame: [FrameHeader DATA flags=END_STREAM stream=5 len=1256]
[5] Sent RST_STREAM on stream 5
[7] Sent HEADERS on stream 7
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=7 len=41]
Received frame: [FrameHeader DATA flags=END_STREAM stream=7 len=1256]
[7] Sent RST_STREAM on stream 7
...
```

The tool is negotiating a connection and then receiving response headers and data (the webpage content). If you reduce the wait and increase the request count it will begin to flood the server. I tested this on nginx by setting my log level to "debug" (but "info" should also work) and watching how the server reacts. You will want to make sure that your server reacts well to a large number of RST_STREAM frames on a single connection. For example, [Envoy added a runtime value](https://github.com/envoyproxy/envoy/security/advisories/GHSA-jhv4-f7mr-xx76) that disconnects the client (presumably sending a GOAWAY frame) after a value is exceeded.

> The mitigation adds a budget on the number of RST_STREAM frames received shortly after corresponding HEADERS frame. The overload.premature_reset_total_stream_count runtime value controls how many prematurely reset streams are tolerated before disconnecting the connection. The default value is 500 and it can be lowered based on your service DoS capacity. The overload.premature_reset_min_stream_lifetime_seconds controls the interval during which the RST_STREAM is considered premature. The default value is 1 second and can be increased based on the profile of the attack. Setting the runtime key envoy.restart_features.send_goaway_for_premature_rst_streams to false completely disables this check.

**Comment by infa-ddeore** [comment]
@secengjeff does below reply look vulnerable? my understanding is yes because i received many frames back, when i compare it with google, cloudflare i receive only 2 frames back

```
$ rapidresetclient -requests=10 -url https://xxx.com:443/ -wait=100 -concurrency=5
Received frame: [FrameHeader SETTINGS flags=ACK len=0]
[3] Sent HEADERS on stream 3
[3] Sent RST_STREAM on stream 3
[5] Sent HEADERS on stream 5
[5] Sent RST_STREAM on stream 5
[7] Sent HEADERS on stream 7
[7] Sent RST_STREAM on stream 7
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=3 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=3 len=107]
[9] Sent HEADERS on stream 9
[9] Sent RST_STREAM on stream 9
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=5 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=5 len=107]
[11] Sent HEADERS on stream 11
[11] Sent RST_STREAM on stream 11
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=7 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=7 len=107]
[13] Sent HEADERS on stream 13
[13] Sent RST_STREAM on stream 13
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=9 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=9 len=107]
[15] Sent HEADERS on stream 15
[15] Sent RST_STREAM on stream 15
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=11 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=11 len=107]
[17] Sent HEADERS on stream 17
[17] Sent RST_STREAM on stream 17
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=13 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=13 len=107]
[19] Sent HEADERS on stream 19
[19] Sent RST_STREAM on stream 19
Received frame: [FrameHeader HEADERS flags=END_HEADERS stream=15 len=31]
Received frame: [FrameHeader DATA flags=END_STREAM stream=15 len=107]
[21] Sent HEADERS on stream 21
[21] Sent RST_STREAM on stream 21

--- Summary ---
Frames sent: HEADERS = 10, RST_STREAM = 10
Frames received: 15
Total time: 2.21 seconds (5 rps)
```

**Comment by secengjeff** [comment]
Try setting requests to something quite large with a low wait time (you could go with zero if you like) and test against a non-production copy of your app. It's really difficult to tell with 10 requests and a 100 ms wait. I just set that as a the example to minimize the possibility of someone accidentally breaking their production app.

Cloudflare and other CDNs like Amazon CloudFront have likely added mitigations that close the connection when many RST_STREAM frames are observed. If you're already behind one of these services you should be in good shape.

**Comment by infa-ddeore** [comment]
thanks for the reply @secengjeff 

this is the summary with 5k requests without any delay, adding only summary output

```
rapidresetclient -requests=10000 -url https://xxx.com:443/ -concurrency=50
...
...
...
--- Summary ---
Frames sent: HEADERS = 9614, RST_STREAM = 9191
Frames received: 281
Total time: 2.98 seconds (3227 rps)
```

so i received 281 frames only

if app is behind AWSs ELB or NLB, app does tls termination, LBs do only L4 routing and doesn't do tls termination, are app vulnerable in this case?

**Comment by secengjeff** [comment]
Any of the ELB products (CLB, ALB, NLB) will terminate TLS but that shouldn't matter for this case. rapidresetclient will open a single TLS session, negotiate SETTINGS once, and then send many HEADERS + RST_STREAM frames. What you're looking for is whether the application can withstand a very high number of these frames. Based on the output that you provided there are two possibilities:

1. The application is failing under the load of these frames and cannot respond to your requests. You would see a HEADERS and a DATA frame in response to each request that you send.
 
2. The application (either your server, your load balancer, or any CDN that you have in front) is recognizing the abnormally large volume of RST_STREAM frames on a single connection and throttling or closing the connection. Throttling may not be visible to you but if the other side closes the connection you would see a single GOAWAY frame.

If you're building a web application on AWS it would make sense to ask AWS how they're handling this. You should also look at using either Amazon CloudFront or Cloudflare if your application can run with a CDN. Both services provide robust DDoS protection to this and many other vectors.

**Comment by infa-ddeore** [comment]
> Any of the ELB products (CLB, ALB, NLB) will terminate TLS but that shouldn't matter for this case. rapidresetclient will open a single TLS session, negotiate SETTINGS once, and then send many HEADERS + RST_STREAM frames. What you're looking for is whether the application can withstand a very high number of these frames. Based on the output that you provided there are two possibilities:
> 
>     1. The application is failing under the load of these frames and cannot respond to your requests. You would see a HEADERS and a DATA frame in response to each request that you send.
> 
>     2. The application (either your server, your load balancer, or any CDN that you have in front) is recognizing the abnormally large volume of RST_STREAM frames on a single connection and throttling or closing the connection. Throttling may not be visible to you but if the other side closes the connection you would see a single GOAWAY frame.
> 
> 
> If you're building a web application on AWS it would make sense to ask AWS how they're handling this. You should also look at using either Amazon CloudFront or Cloudflare if your application can run with a CDN. Both services provide robust DDoS protection to this and many other vectors.

thanks for the reply, my bad that I pasted the command with 50k request but it was 10k request output, i corrected the command in my previous comment.

So shall i assume that with 10k requests, i received 9614 headers and 9191 rst streams that means my app is vulnerable?

**Comment by secengjeff** [comment]
It is difficult to tell from only the summary. The only thing I can conclude from this summary is that the server did not respond to every request that you sent. You would need to look at your server/application metrics and see whether it continued to function as expected. You can also look at debug level logs for your web server and see how it reacted to a large volume of RST_STREAM frames on a single connection. My guess is that the server either could not respond or chose not to respond.
